### ISSUE TITLE
fido

### ISSUE THREAD

**Issue by jayvdb** [jayvdb/anyhttp#17]
`fido` was blocked from testing by way of being in `http_tests.threading_problems`, without any further comment.

Its handler now fails with

```py
  File "anyhttp/__init__.py", line 232, in raw
    result = result.result()
AttributeError: 'EventualResult' object has no attribute 'result'
```

`result()` works with fido 1.0.0, and it should be `wait()` for recent futures

**Comment by jayvdb** [comment]
Initial commit https://github.com/jayvdb/anyhttp/commit/4d2b06e2f288995625e6060ae1229b576617e324#diff-e896e4860d46215a65acfa06745711aa89bf35fa38bf0b573e5530ca41592bceR33 listed three packages, but mentions only two.
```py
# These two cause the following exception if run as scenario:
# NotImplementedError: gevent is only usable from a single thread
threading_problems = ['fido', 'asynchttp', 'httxlib']
```

HttxLib seems to break requests and other packages even before it is tested.
https://travis-ci.org/github/jayvdb/anyhttp/jobs/736347318

The problems with asynchttp seems to be fixed now on py27.
